version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    groups:
      actions:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'

    open-pull-requests-limit: 10

    versioning-strategy: increase

    labels:
      - 'dependencies'

    commit-message:
      prefix: 'chore'
      include: 'scope'

    groups:
      typescript:
        patterns:
          - 'typescript'
          - 'typescript-eslint'
          - '@types/*'

      eslint:
        patterns:
          - 'eslint'
          - 'eslint-config-prettier'
          - 'eslint-plugin-prettier'
          - '@eslint/*'
          - 'globals'

      prettier:
        patterns:
          - 'prettier'

      turbo:
        patterns:
          - 'turbo'

      vitest:
        patterns:
          - 'vitest'